import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// RTK Query API slice for domain-related operations
export const domainApi = createApi({
  reducerPath: "domainApi",
  baseQuery: fetchBaseQuery({
    baseUrl: "https://6797aa2bc2c861de0c6d964c.mockapi.io/domain", 
  }),
  tagTypes: ["Domain"],
  endpoints: (builder) => ({
    // Fetch all domains
    getDomains: builder.query({
      query: () => "",
      providesTags: ["Domain"],
    }),

    // Fetch a single domain by ID
    getDomainById: builder.query({
      query: (id) => `/${id}`,
    }),

    // Create a new domain
    addDomain: builder.mutation({
      query: (newDomain) => ({
        url: "",
        method: "POST",
        body: {
          createdDate: newDomain.createdDate || Math.floor(Date.now() / 1000),
          domain: newDomain.domain,
          status: newDomain.status,
          isActive: newDomain.isActive,
        },
      }),
      invalidatesTags: ["Domain"],
    }),

    // Update an existing domain
    updateDomain: builder.mutation({
      query: ({ id, domain, isActive, status }) => ({
        url: `/${id}`,
        method: "PUT",
        body: {
          ...(domain !== undefined && { domain }),
          ...(isActive !== undefined && { isActive }),
          ...(status !== undefined && { status }),
        },
      }),
      invalidatesTags: ["Domain"],
    }),

    // Delete a domain by ID
    deleteDomain: builder.mutation({
      query: (id) => ({
        url: `/${id}`,
        method: "DELETE",
      }),
      invalidatesTags: ["Domain"],
    }),
  }),
});

// Export hooks auto-generated by RTK Query
export const {
  useGetDomainsQuery,
  useGetDomainByIdQuery,
  useAddDomainMutation,
  useUpdateDomainMutation,
  useDeleteDomainMutation,
} = domainApi;
